import React from 'react';
import { Download, FileText, Calendar, User, BarChart3, Target, Clock, Award } from 'lucide-react';
import { PitchAnalysis } from '../services/aiAnalysisService';

interface PDFExportProps {
  analysis: PitchAnalysis;
  transcript: string;
  userName?: string;
  pitchTitle?: string;
  language?: string;
  onExport: () => void;
  className?: string;
}

const PDFExport: React.FC<PDFExportProps> = ({
  analysis,
  transcript,
  userName = 'Anonymous User',
  pitchTitle = 'Untitled Pitch',
  language = 'English',
  onExport,
  className = ''
}) => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const generatePDFContent = () => {
    // This would integrate with jsPDF or similar library
    // For now, we'll create a preview of what the PDF would contain
    
    const pdfContent = `
PITCHSENSE ANALYSIS REPORT
${pitchTitle}
Generated on ${currentDate}

PRESENTER: ${userName}
LANGUAGE: ${language}
DURATION: ${analysis.estimatedDuration} seconds
WORD COUNT: ${analysis.wordCount} words

OVERALL SCORE: ${analysis.overallScore}/10

DETAILED SCORES:
• Clarity: ${analysis.clarity.score}/10 - ${analysis.clarity.feedback}
• Tone: ${analysis.tone.score}/10 - ${analysis.tone.feedback}
• Pacing: ${analysis.pacing.score}/10 - ${analysis.pacing.feedback}
• Structure: ${analysis.structure.score}/10 - ${analysis.structure.feedback}

FILLER WORDS ANALYSIS:
• Count: ${analysis.fillerWords.count}
• Percentage: ${analysis.fillerWords.percentage}%
• Examples: ${analysis.fillerWords.examples.join(', ')}

PITCH STRUCTURE ELEMENTS:
${Object.entries(analysis.structure)
  .filter(([key]) => key.startsWith('has'))
  .map(([key, value]) => `• ${key.replace('has', '').replace(/([A-Z])/g, ' $1').trim()}: ${value ? '✓' : '✗'}`)
  .join('\n')}

STRENGTHS:
${analysis.strengths.map(strength => `• ${strength}`).join('\n')}

IMPROVEMENT SUGGESTIONS:
${analysis.improvements.map(improvement => `• ${improvement}`).join('\n')}

MISSING ELEMENTS:
${analysis.missingElements.map(element => `• ${element}`).join('\n')}

TRANSCRIPT:
${transcript}

---
Generated by PitchSense AI Pitch Coach
www.pitchsense.ai
    `.trim();

    return pdfContent;
  };

  const handleExport = () => {
    // In a real implementation, this would use jsPDF
    const content = generatePDFContent();
    
    // For demo purposes, we'll download as a text file
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PitchSense_Analysis_${pitchTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    onExport();
  };

  return (
    <div className={`bg-gradient-to-br from-gray-900/60 to-gray-800/40 rounded-2xl p-6 border border-gray-600/30 ${className}`}>
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-3">
          <div className="w-10 h-10 bg-green-500/20 rounded-xl flex items-center justify-center">
            <FileText className="w-5 h-5 text-green-400" />
          </div>
          <div>
            <h3 className="text-lg font-semibold text-white">Export Analysis Report</h3>
            <p className="text-sm text-gray-400">Download a comprehensive PDF report</p>
          </div>
        </div>
        
        <button
          onClick={handleExport}
          className="px-6 py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white font-semibold rounded-xl hover:shadow-lg transition-all duration-300 flex items-center space-x-2"
        >
          <Download className="w-4 h-4" />
          <span>Export PDF</span>
        </button>
      </div>

      {/* PDF Preview */}
      <div className="bg-black/20 rounded-xl p-6 space-y-4">
        <div className="text-center border-b border-gray-600/30 pb-4">
          <div className="flex items-center justify-center space-x-2 mb-2">
            <div className="w-8 h-8 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg flex items-center justify-center">
              <BarChart3 className="w-4 h-4 text-white" />
            </div>
            <h4 className="text-xl font-bold text-white">PitchSense Analysis Report</h4>
          </div>
          <p className="text-gray-300 text-sm">{pitchTitle}</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div className="bg-gray-800/40 rounded-lg p-4">
            <div className="flex items-center space-x-2 mb-2">
              <User className="w-4 h-4 text-blue-400" />
              <span className="text-sm font-medium text-white">Presenter</span>
            </div>
            <p className="text-gray-300">{userName}</p>
          </div>

          <div className="bg-gray-800/40 rounded-lg p-4">
            <div className="flex items-center space-x-2 mb-2">
              <Calendar className="w-4 h-4 text-green-400" />
              <span className="text-sm font-medium text-white">Date</span>
            </div>
            <p className="text-gray-300">{currentDate}</p>
          </div>

          <div className="bg-gray-800/40 rounded-lg p-4">
            <div className="flex items-center space-x-2 mb-2">
              <Award className="w-4 h-4 text-purple-400" />
              <span className="text-sm font-medium text-white">Overall Score</span>
            </div>
            <p className="text-2xl font-bold text-white">{analysis.overallScore}/10</p>
          </div>
        </div>

        <div className="space-y-3">
          <h5 className="text-sm font-semibold text-white flex items-center space-x-2">
            <Target className="w-4 h-4" />
            <span>Report Contents</span>
          </h5>
          
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2 text-sm">
            <div className="flex items-center space-x-2 text-gray-300">
              <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
              <span>Detailed score breakdown</span>
            </div>
            <div className="flex items-center space-x-2 text-gray-300">
              <div className="w-2 h-2 bg-green-400 rounded-full"></div>
              <span>Improvement suggestions</span>
            </div>
            <div className="flex items-center space-x-2 text-gray-300">
              <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
              <span>Structure analysis</span>
            </div>
            <div className="flex items-center space-x-2 text-gray-300">
              <div className="w-2 h-2 bg-yellow-400 rounded-full"></div>
              <span>Full transcript</span>
            </div>
            <div className="flex items-center space-x-2 text-gray-300">
              <div className="w-2 h-2 bg-red-400 rounded-full"></div>
              <span>Filler words analysis</span>
            </div>
            <div className="flex items-center space-x-2 text-gray-300">
              <div className="w-2 h-2 bg-indigo-400 rounded-full"></div>
              <span>Professional formatting</span>
            </div>
          </div>
        </div>

        <div className="pt-4 border-t border-gray-600/30">
          <div className="flex items-center justify-between text-xs text-gray-400">
            <span>Generated by PitchSense AI</span>
            <div className="flex items-center space-x-4">
              <span className="flex items-center space-x-1">
                <Clock className="w-3 h-3" />
                <span>{analysis.estimatedDuration}s duration</span>
              </span>
              <span className="flex items-center space-x-1">
                <FileText className="w-3 h-3" />
                <span>{analysis.wordCount} words</span>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PDFExport;